### PR TITLE
Bump version to `1.9.2`

### PR DESCRIPTION
**Pull request by andreimoustache**

### CODE REVIEW

**Review by octavz — APPROVED** [review]

**Comment by containerpope** [comment]
I am currently a little busy, hope I will be able to review it soon, but first, the CICD system has to be adjusted, because of java8.

**Comment by andreimoustache** [comment]
Hi, Matthias!

No worries, when you have time! Yes, I saw that the build server doesn't like something, but I don't really get what the issue is. Please let me know if you think there's something that I could do to help!

**Comment by containerpope** [comment]
@andreimoustache It was just that travis ci didn't support anymore builds on java8, so I switched to circle ci. Now everything should run well again.

**Comment by andreimoustache** [comment]
Awesome, thank you very much!

**Pull request merged**
